// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-9LuymrKZpPM68Gc5IvNt7cK5KLnKilU',
    appId: '1:155793648455:web:f3adc68bea123058cffa62',
    messagingSenderId: '155793648455',
    projectId: 'barberappversionone',
    authDomain: 'barberappversionone.firebaseapp.com',
    storageBucket: 'barberappversionone.firebasestorage.app',
    measurementId: 'G-QYQL8F1JRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_P2OgCnuyvQcDSj7mKul3ZXZ1q_6Up28',
    appId: '1:155793648455:android:37aa64628f610e8ecffa62',
    messagingSenderId: '155793648455',
    projectId: 'barberappversionone',
    storageBucket: 'barberappversionone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4_WfLNadHWS0dQ8wwG7bJzkIe2Y4UcBQ',
    appId: '1:155793648455:ios:c2450a1ad58c4877cffa62',
    messagingSenderId: '155793648455',
    projectId: 'barberappversionone',
    storageBucket: 'barberappversionone.firebasestorage.app',
    iosBundleId: 'com.example.barberBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4_WfLNadHWS0dQ8wwG7bJzkIe2Y4UcBQ',
    appId: '1:155793648455:ios:c2450a1ad58c4877cffa62',
    messagingSenderId: '155793648455',
    projectId: 'barberappversionone',
    storageBucket: 'barberappversionone.firebasestorage.app',
    iosBundleId: 'com.example.barberBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-9LuymrKZpPM68Gc5IvNt7cK5KLnKilU',
    appId: '1:155793648455:web:0d9c070ecab74f1ecffa62',
    messagingSenderId: '155793648455',
    projectId: 'barberappversionone',
    authDomain: 'barberappversionone.firebaseapp.com',
    storageBucket: 'barberappversionone.firebasestorage.app',
    measurementId: 'G-4PHBFBZDQC',
  );
}
